apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data-dev 
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/appz/volumes/dev/mariadb/data 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nhpri-rollout-node-01
